// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Pathology.Services.TestAPI.Data;


#nullable disable

namespace Pathology.Services.TestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pathology.Services.TestAPI.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("TestId");

                    b.ToTable("tests");

                    b.HasData(
                        new
                        {
                            TestId = 1,
                            CategoryName = "NA",
                            Description = " NA",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "FBC",
                            Price = 15.0
                        },
                        new
                        {
                            TestId = 2,
                            CategoryName = "NA",
                            Description = "NA",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Lipid",
                            Price = 13.99
                        },
                        new
                        {
                            TestId = 3,
                            CategoryName = "NA",
                            Description = "NA",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "LFT",
                            Price = 10.99
                        },
                        new
                        {
                            TestId = 4,
                            CategoryName = "NA",
                            Description = "NA",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Sugar",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
